### ISSUE TITLE
[UI] As a logged-in user, I can receive notifications when I got mentioned.

### ISSUE THREAD

**Issue by suho** [nimblehq/github-notifications-mac#30]
## Why

We need to support the logged-in user to receive notifications when they got mentioned.

## Acceptance Criteria

- Use the default notification banner from Apple
For example:
- App Name: `Github Notifications` 
- Title: `nimblehq/ios-templates` (repository name)
- Description: `Mentioned on: [#143] Add Github Action template`

Design: https://www.figma.com/file/jCSHtb5pycYvT57B5MZaSu/Github-Notifications?node-id=7%3A570

**Comment by blyscuit** [comment]
@markgravity This can be done together with https://github.com/nimblehq/github-notifications-mac/issues/38. I assigned this to you because they are related. Feel free to notify us if not enough time.
