### ISSUE TITLE
[Integrate] As a logged-in user, when I press on the `review request` notification banner, in case I enable the option repeat review requested notification, I don't want to show that banner again

### ISSUE THREAD

**Issue by suho** [nimblehq/github-notifications-mac#99]
## Why

When the user enables to option `repeat review requested notifications`. Currently, we always repeat the notifications even when the user has pressed on that banner and reviewed it.
We need to support turn off the repetition for the notifications that the user already pressed on it.
 
## Acceptance Criteria

When the user press on the notification banner, if the notification is a review requested notification and the option `repeat review requested notifications` is on, then we remove only that notification out of the repeat notifications list.

**Comment by blyscuit** [comment]
I think this is done in https://github.com/nimblehq/github-notifications-mac/pull/92/files. Let me check for this bug.
